# Generated by Django 5.1.6 on 2025-03-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='resourceauthor',
            options={'ordering': ['resource__title', 'order']},
        ),
    ]
