# Generated by Django 5.1.6 on 2025-03-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_result_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.IntegerField(blank=True, choices=[(0, 'Computing'), (1, 'Engineering'), (2, 'Mathematics'), (3, 'Sciences'), (4, 'Medicine'), (5, 'Languages'), (6, 'Humanities'), (10, 'Other')], null=True)),
                ('age_group', models.IntegerField(blank=True, choices=[(0, 'Elementary School (K-5)'), (1, 'Middle School (6-8)'), (2, 'High School (9-12)'), (3, 'Undergraduate'), (4, 'Graduate'), (5, 'Other')], null=True)),
                ('outcomes', models.ManyToManyField(to='myapp.outcome')),
            ],
            options={
                'ordering': ['created_at', 'name'],
                'unique_together': {('name',)},
            },
        ),
    ]
