# Generated by Django 5.2.15 on 2026-08-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_scenario_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('name',)},
        ),
    ]
